### ISSUE TITLE
Use native Symbol.asyncIterator if available

### ISSUE THREAD

**Issue by MeirionHughes** [MeirionHughes/levelup-async-iterator#1]
* if `this._db.iterator()[Symbol.asyncIterator] !== undefined)`
  * don't override it and return `it`

**Comment by huan** [comment]
Oh, sorry I just saw this issue. That's what I purposed in #2 because I'm just writing a wrapper of levelup db to use the async iterator. 

See: https://github.com/zixia/face-blinder/blob/38ba45f263cc5cd892d034f8b115b470ed30bf0e/src/store.ts#L114

**Comment by huan** [comment]
Do you want to include this feature in the official `levelup` package in the future?

I suggest so because after doing that, users will be very convenient to use the async iterator.

**Comment by MeirionHughes** [comment]
I think the end-goal would be to add this to the levelup / leveldown implementations _eventually_. 

Node is supposedly getting async-iterator support on streams - so Level guys may well _not_ add direct access to the iterator from level-up and tell you to use the stream instead.
